### ISSUE TITLE
Add a search bar to the order list page

### ISSUE THREAD

**Issue by paulrang** [499-GroupB/CampOAC-GroupB#190]

**Comment by boulongadong** [comment]
good idea

**Comment by onlinestang** [comment]
Will need to change the order API

**Comment by onlinestang** [comment]
> Will need to change the order API

Or add a table filter

**Comment by onlinestang** [comment]
Donezo
![image](https://user-images.githubusercontent.com/20649040/230846316-db6111e2-cf70-4d12-854c-20fa2531dac8.png)
