### ISSUE TITLE
Alignment of table in admin page

### ISSUE THREAD

**Issue by SaiRohithEnumala8373** [499-GroupB/CampOAC-GroupB#221]
<img width="1466" alt="Screenshot 2023-01-22 at 2 13 17 PM" src="https://user-images.githubusercontent.com/90168677/213943125-4d126066-b5b9-4196-ad75-b9f187d88f28.png">

<img width="1048" alt="1" src="https://user-images.githubusercontent.com/90168677/213943179-287e4b47-602c-449c-8931-4116c44ff626.png">

**Comment by SaiRohithEnumala8373** [comment]
<img width="1470" alt="Screenshot 2023-01-22 at 2 16 18 PM" src="https://user-images.githubusercontent.com/90168677/213943259-071bd747-a61d-4672-9702-341d267078bb.png">

**Comment by paulrang** [comment]
Probably fixed with #235
