### ISSUE TITLE
Can't order more than 1 bag

### ISSUE THREAD

**Issue by paulrang** [499-GroupB/CampOAC-GroupB#348]
If you order more than one bag, only 1 goes through

**Comment by SaiRohithEnumala8373** [comment]
<img width="1468" alt="Screenshot 2023-03-22 at 9 52 18 AM" src="https://user-images.githubusercontent.com/90168677/226979414-039e4ac8-3644-4b2c-b564-48865f802483.png">

**Comment by paulrang** [comment]
<img width="376" alt="12" src="https://user-images.githubusercontent.com/77507367/226980155-e11f4b21-711f-467a-b7d6-a065334620dd.PNG">
<img width="407" alt="13" src="https://user-images.githubusercontent.com/77507367/226980152-d26ca6ef-c682-48f7-bce1-e4dc78f6b460.PNG">

**Comment by onlinestang** [comment]
On it

**Comment by onlinestang** [comment]
Solved as of #359

**Comment by onlinestang** [comment]
Done
