### ISSUE TITLE
Design layout (store page)

### ISSUE THREAD

**Issue by onlinestang** [499-GroupB/CampOAC-GroupB#37]
Need to agree on a layout for the site. Where things will be and a good reason for them to be there

**Comment by boulongadong** [comment]
[Rotary Graphic Standards.pdf](https://github.com/499-GroupB/CampOAC-GroupB/files/9847595/Rotary.Graphic.Standards.pdf)

**Comment by boulongadong** [comment]
[paperPrototype1_michael.pdf](https://github.com/499-GroupB/CampOAC-GroupB/files/9891786/paperPrototype1_michael.pdf)

**Comment by boulongadong** [comment]
![Paul_Mockup1](https://user-images.githubusercontent.com/77290153/198731102-5fe9b147-e017-4c70-9508-d61752b38494.png)
![Paul_Mockup2](https://user-images.githubusercontent.com/77290153/198731104-a539d6a3-4ec1-4266-a2ef-9ff05846130b.png)
![Paul_Mockup3](https://user-images.githubusercontent.com/77290153/198731106-6841676f-28e9-4373-a943-d9e854c4798d.png)
![Paul_Mockup4](https://user-images.githubusercontent.com/77290153/198731109-42a44727-e13d-470b-be25-f16e12c03de9.png)
![Paul_Mockup5](https://user-images.githubusercontent.com/77290153/198731110-9bee442d-c654-4284-bbeb-f826c97b4285.png)
![Paul_Mockup6](https://user-images.githubusercontent.com/77290153/198731111-6f9e41f6-8858-46eb-9f26-11b4ca9314fb.png)

**Comment by SaiRohithEnumala8373** [comment]
Uploaded to repo
