### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by boulongadong** [499-GroupB/CampOAC-GroupB#53]
Define schema for database

**Comment by onlinestang** [comment]
Database schema for Orders is set, possible to change in future

tentative User schema is: id, email, username, password.

**Comment by onlinestang** [comment]
Revision:

Order schema needs a reference to Location
Location schema: { name: string, stock: number, active: boolean }
active flag allows for admins to temporarily close a location for whatever reason
stock allows for admin to change stock
name will be used in the order schema to link orders with specific locations when admin needs to filter orders.

**Comment by onlinestang** [comment]
This schema should work until further notice
#197
