### ISSUE TITLE
Database Pricing

### ISSUE THREAD

**Issue by boulongadong** [499-GroupB/CampOAC-GroupB#55]
Decide on best pricing tier for database

**Comment by SaiRohithEnumala8373** [comment]
https://www.mongodb.com/pricing?utm_source=google&utm_campaign=search_gs_pl_evergreen_atlas_general_prosp-brand_gic-null_amers-ca_ps-all_desktop_eng_lead&utm_term=mongo%20data%20base&utm_medium=cpc_paid_search&utm_ad=p&utm_ad_campaign_id=1718986501&adgroup=66929790666&gclid=Cj0KCQjwqoibBhDUARIsAH2OpWjlRNT4o4DVDjQIIPh0ylM9kWbth4ymnnuopooKu037Zuo2ROsJLHEaAmHVEALw_wcB

**Comment by SaiRohithEnumala8373** [comment]
Done!
