### ISSUE TITLE
Visual Prototypes

### ISSUE THREAD

**Issue by boulongadong** [499-GroupB/CampOAC-GroupB#62]
Digital prototypes (store/admin)

**Comment by boulongadong** [comment]
<img width="910" alt="visPro_admin" src="https://user-images.githubusercontent.com/77290153/199553956-593f8400-34c6-4bcd-92e0-c0c47d20ad20.png">
<img width="968" alt="visPro_home" src="https://user-images.githubusercontent.com/77290153/199553962-da0eaea9-4ead-4c0b-b76e-69bd482b2468.png">
<img width="923" alt="visPro_order" src="https://user-images.githubusercontent.com/77290153/199553964-561f1bad-af81-4d98-af24-8a326ee1ba47.png">
<img width="964" alt="visPro_thanks" src="https://user-images.githubusercontent.com/77290153/199553965-2ce159a9-df80-4a4f-a1f7-18bb41a00eda.png">

**Comment by SaiRohithEnumala8373** [comment]
Thank you!
