### ISSUE TITLE
Share Visual Prototype w/ Client

### ISSUE THREAD

**Issue by boulongadong** [499-GroupB/CampOAC-GroupB#66]
Involving the client in the prototype stage will ensure we are on the right path from the beginning and could save costly restructurings down the line.

**Comment by SaiRohithEnumala8373** [comment]
Yeah, I agree.

**Comment by paulrang** [comment]
We ought to show them Michael's mockups.

**Comment by boulongadong** [comment]
We have sent prototypes to client, awaiting feedback
